services:
  - type: web
    name: reflex-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    buildCommand: next build
    startCommand: reflex run
    autoDeploy: true
